site_name: MRQ
theme: readthedocs
dev_addr: '0.0.0.0:8000'
pages:

- ["index.md", "Introduction"]
- ["get-started.md", "Get Started"]

- ["jobs.md", "Basic usage", "Jobs & Tasks"]
- ["workers.md", "Basic usage", "Workers"]
- ["queues.md", "Basic usage", "Queues"]
- ["configuration.md", "Basic usage", "Configuration"]
- ["command-line.md", "Basic usage", "Command line"]

- ["dashboard.md", "Visibility", "Dashboard"]
- ["memory-leaks.md", "Visibility", "Hunting memory leaks"]
- ["metrics.md", "Visibility", "Metrics"]
- ["io-monitoring.md", "Visibility", "I/O Monitoring"]

- ["design.md", "Advanced", "Design and architecture"]
- ["performance.md", "Advanced", "Performance"]
- ["recurring-jobs.md", "Advanced", "Recurring jobs"]
- ["jobs-maintenance.md", "Advanced", "Jobs maintenance"]
- ["best-practices.md", "Advanced", "Best practices"]

- ["contributing.md", "About MRQ", "Contributing"]
- ["tests.md", "About MRQ", "Tests"]
- ["changelog.md", "About MRQ", "Changelog"]
- ["dependencies.md", "About MRQ", "Dependencies & credits"]
- ["license.md", "About MRQ", "License"]
